import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'
import React, { PureComponent } from 'react'
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts'
import _ from 'lodash'
import randomColor from 'randomcolor'
import { Line as LineChartJs } from 'react-chartjs-2';

const fetcher = async (url) => {
  const response = await fetch(url)
  return await response.json()
}



export default function Home() {
  const { data, error } = useSWR('/api/fetch', fetcher)

  if (!data) return "Loading"

  const datasets = _.map(_.groupBy(data.data, 'title'), ( values, title) => {
    const color = randomColor({seed: title})
    return {
      label: title,
      backgroundColor: color,
      borderColor: color,
      data: values.map(value => ({
        y: value.readers,
        x: value.time['@ts'],

      }))
    }
  })
  const chartData = {
    datasets
  }

  const options = {
    plugins: {
      legend: {
        position: 'bottom'
      }
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LineChartJs data={chartData} options={options}/>



    </div>
  )
}
