import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'
import React, { PureComponent } from 'react'
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts'
import _ from 'lodash'


const fetcher = async (url) => {

  const response = await fetch(url)
  return await response.json()

}

export default function Home() {
  const { data, error } = useSWR('/api/fetch', fetcher)

  if (!data) return "Loading"

  console.log(data.data)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <ResponsiveContainer width={"100%"} height={500}>
        <LineChart width={700} height={300} data={data.data}>
          <XAxis dataKey="time.@ts" />
          <YAxis dataKey="readers" />
          <Tooltip />
          <Legend />
          <Line type="monotone" dataKey="readers" stroke="#8884d8" strokeWidth={2} />
        </LineChart> 
        </ResponsiveContainer>
    </div>
  )
}
